export interface DailyDoaItem {
  id: string;
  number: number;
  title: string;
  category: string;
  arabic: string;
  latin: string;
  translation: string;
  source?: string;
  surahNumber?: number;
  surahName?: string;
  verseNumber?: number;
}

export const DOA_CATEGORIES = [
  { id: 'all', label: 'Semua Doa (40)' },
  { id: 'Pagi & Malam', label: 'Pagi & Malam' },
  { id: 'Kamar Mandi & Pakaian', label: 'Kamar Mandi & Pakaian' },
  { id: 'Makan & Bepergian', label: 'Makan & Bepergian' },
  { id: 'Ibadah', label: 'Ibadah & Sholat' },
  { id: 'Belajar & Majelis', label: 'Belajar & Majelis' },
  { id: 'Ketenangan & Rezeki', label: 'Ketenangan & Rezeki' },
  { id: 'Keluarga & Sesama', label: 'Keluarga & Sesama' },
  { id: 'Alam & Musibah', label: 'Alam & Musibah' },
  { id: 'Kesehatan & Keselamatan', label: 'Kesehatan & Keselamatan' },
];

export const DAILY_DOA_LIST: DailyDoaItem[] = [
  // 1. Doa Pagi dan Malam Hari (1 - 7)
  {
    id: 'doa-1',
    number: 1,
    title: 'Doa Pagi Hari',
    category: 'Pagi & Malam',
    arabic: 'اَللّٰهُمَّ بِكَ اَصْبَحْنَا وَبِكَ اَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوْتُ وَاِلَيْكَ النُّشُوْرُ',
    latin: 'Allahumma bika ashbahnaa wa bika amsainaa wa bika nahyaa wa bika namuutu wa ilaikan nusyuuru.',
    translation: 'Ya Allah, karena Engkau kami mengalami waktu pagi dan waktu petang, dan karena Engkau kami hidup dan mati dan kepada-Mu juga kami akan kembali.',
    source: 'Doa Harian Nabawi',
  },
  {
    id: 'doa-2',
    number: 2,
    title: 'Doa Bangun Tidur',
    category: 'Pagi & Malam',
    arabic: 'الحَمْدُ لِلهِ الَّذِيْ أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُوْرُ',
    latin: 'Alhamdulillahil ladzi ahyana ba\'da ma amatana wa ilaihin nusyur.',
    translation: 'Segala puji bagi Allah, Tuhan yang menghidupkan kami setelah Ia mematikan kami. Kepada-Nya lah kebangkitan hari kiamat.',
    source: 'HR. Bukhari & Muslim',
  },
  {
    id: 'doa-3',
    number: 3,
    title: 'Doa Sebelum Tidur',
    category: 'Pagi & Malam',
    arabic: 'بِاسْمِكَ اللهُمَّ أَحْيَا وَأَمُوْتُ',
    latin: 'Bismika Allahumma ahyaa wa bismika amuut.',
    translation: 'Dengan menyebut nama Allah yang menghidupkan dan mematikan.',
    source: 'HR. Bukhari & Muslim',
  },
  {
    id: 'doa-4',
    number: 4,
    title: 'Doa Agar Memperoleh Mimpi Baik',
    category: 'Pagi & Malam',
    arabic: 'اَللّٰهُمَّ أَرِنَا الْحَقَّ حَقًّا وَارْزُقْنَا اتِّـبَاعَهُ وَأَرِنَا الْبَاطِلَ بَاطِلًا وَارْزُقْنَا اجْتِنَابَهُ',
    latin: 'Allahumma arinal haqqa haqqan warzuqnat tibaa\'ahu. Wa arinal baathila baathilan warzuqnajtina bahu.',
    translation: 'Ya Allah, tunjukkanlah kepada kami kebenaran sehingga kami bisa mengikutinya, dan tunjukkanlah kepada kami kejelekan sehingga kami dapat menjauhinya.',
  },
  {
    id: 'doa-5',
    number: 5,
    title: 'Doa Jika Memperoleh Mimpi Baik',
    category: 'Pagi & Malam',
    arabic: 'اَلْحَمْدُ للَّهِ رَبِّ الْعالَمِينَ',
    latin: 'Alhamdulillahi rabbil \'aalamiin.',
    translation: 'Segala puji bagi Allah, Tuhan seluruh alam.',
  },
  {
    id: 'doa-6',
    number: 6,
    title: 'Doa Mimpi Buruk',
    category: 'Pagi & Malam',
    arabic: 'اللَّهمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَمَل الشَّيْطَانِ وَسَيِّئَاتِ الْأَحْلَامِ',
    latin: 'Allaahumma innii a\'uudzubika min \'amalisy syaithaani wasayyi-aatil ahlaami.',
    translation: 'Ya Allah, sesungguhnya aku berlindung kepada-Mu dari perbuatan syaitan dan keburukan mimpi.',
  },
  {
    id: 'doa-7',
    number: 7,
    title: 'Doa Dimudahkan Segala Urusan',
    category: 'Pagi & Malam',
    arabic: 'رَبَّنَا آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا رَبِّ اشْرَحْ لِي صَدْرِي، وَيَسِّرْ لِي أَمْرِي',
    latin: 'Rabbana atina min ladunka rahmatan, wa hayyi\' lana min amrina rasyadan, rabbisyrah li shadri, wa yassir li amri.',
    translation: 'Wahai Tuhan kami, berikanlah rahmat kepada kami dari sisi-Mu dan sempurnakanlah bagi kami petunjuk yang lurus dalam urusan kami ini. Ya Tuhanku, lapangkanlah untukku dadaku, dan mudahkanlah untukku urusanku.',
    surahNumber: 18,
    surahName: 'Al-Kahf',
    verseNumber: 10,
    source: 'QS. Al-Kahf: 10 & QS. Taha: 25-26',
  },

  // 2. Doa di Kamar Mandi dan Berpakaian (8 - 13)
  {
    id: 'doa-8',
    number: 8,
    title: 'Doa Masuk Kamar Mandi',
    category: 'Kamar Mandi & Pakaian',
    arabic: 'بِسْمِ اللهِ اللَّهُمَّ إنِّي أَعُوذُ بِك مِنَ الْخُبْثِ وَالْخَبَائِثِ',
    latin: 'Bismillahi Allahumma inni a\'udzu bika minal khubutsi wal khabaitsi.',
    translation: 'Ya Allah, aku berlindung pada-Mu dari godaan iblis jantan dan betina.',
    source: 'HR. Bukhari & Muslim',
  },
  {
    id: 'doa-9',
    number: 9,
    title: 'Doa Keluar Kamar Mandi',
    category: 'Kamar Mandi & Pakaian',
    arabic: 'الْحَمْدُ لِلهِ الَّذِي أَذْهَبَ عَنِّي الْأَذَى وَعَافَانِي',
    latin: 'Alhamdulillahi alladzi adzhaba \'anni al-adza wa\'aafaani.',
    translation: 'Segala puji bagi Allah yang telah menghilangkan penyakit dari tubuhku dan menyehatkan aku.',
    source: 'HR. Ibnu Majah',
  },
  {
    id: 'doa-10',
    number: 10,
    title: 'Doa Melepaskan Pakaian',
    category: 'Kamar Mandi & Pakaian',
    arabic: 'بِسْمِ اللهِ الَّذِيْ لَا إِلهَ إِلاَّ هُوَ',
    latin: 'Bismillahil ladzi lailaha illa huwa.',
    translation: 'Dengan nama Allah yang tiada Tuhan selain Dia.',
    source: 'HR. Ibnu Sunni',
  },
  {
    id: 'doa-11',
    number: 11,
    title: 'Doa Memakai Pakaian',
    category: 'Kamar Mandi & Pakaian',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَا هُوَ لَهُ ، وَأَعُوْذُ بِكَ مِنْ شَرِّهِ وَشَرِّ مَا هُوَ لَهُ',
    latin: 'Allahumma inni as\'aluka min khairihi wa khaira ma huwa lahu, wa a\'udzubika min syarrihi wa syarri ma huwa lahu.',
    translation: 'Ya Allah, sesungguhnya aku memohon kepada-Mu kebaikan pakaian ini dan kebaikan sesuatu yang di dalamnya, dan aku berlindung kepada-Mu dari keburukan pakaian ini dan keburukan sesuatu yang ada di dalamnya.',
    source: 'HR. Abu Dawud & Tirmidzi',
  },
  {
    id: 'doa-12',
    number: 12,
    title: 'Doa Memakai Baju Baru',
    category: 'Kamar Mandi & Pakaian',
    arabic: 'الحَمْدُ لِلَّهِ الَّذِي كَساني ما أُوَاري بِهِ عَوْرَتي وَأَتَجَمَّلُ بِهِ في حياتي',
    latin: 'Alhamdulillahil ladzi kasani ma uwariy bihi\'aurati wa atajammalu bihi fi hayati.',
    translation: 'Segala puji bagi Allah yang telah memberiku pakaian sebagai penutup auratku dan penghias dalam hidupku.',
    source: 'HR. Tirmidzi',
  },
  {
    id: 'doa-13',
    number: 13,
    title: 'Doa Ketika Bercermin',
    category: 'Kamar Mandi & Pakaian',
    arabic: 'اَللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِيْ فَحَسِّنْ خُلُقِيْ',
    latin: 'Allahumma kama hassanta khalqi fahassin khuluqi.',
    translation: 'Wahai Allah, sebagaimana telah Kau baguskan kejadianku, maka baguskanlah perangaiku.',
    source: 'HR. Ahmad & Ibnu Hibban',
  },

  // 3. Doa Makan dan Bepergian (14 - 18)
  {
    id: 'doa-14',
    number: 14,
    title: 'Doa Sebelum Makan',
    category: 'Makan & Bepergian',
    arabic: 'اللَّهُمَّ بَارِكْ لَناَ فِيْمَا رَزَقْتَنا وَقِنَا عَذَابَ النَّارِ، بِسْمِ اللهِ',
    latin: 'Allahumma barik lana fi ma razaqtana wa qina adzaban nar, bismillah.',
    translation: 'Ya Allah, berkahilah kami pada apa yang telah Engkau karuniakan dan lindungilah kami dari siksa neraka. Bismillah (atas nama Allah).',
    source: 'HR. Ibnu Sunni',
  },
  {
    id: 'doa-15',
    number: 15,
    title: 'Doa Sesudah Makan',
    category: 'Makan & Bepergian',
    arabic: 'اَلْحَمْدُ لِلهِ الَّذِيْ أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مِنَ المُسْلِمِيْنَ',
    latin: 'Alhamdulillahilladzi ath\'amana wa saqana wa ja\'alana minal muslimin.',
    translation: 'Segala puji bagi Allah yang telah memberi kami makan dan telah memberi kami minum, dan menjadikan kami termasuk orang yang patuh.',
    source: 'HR. Abu Dawud & Tirmidzi',
  },
  {
    id: 'doa-16',
    number: 16,
    title: 'Doa Keluar Rumah',
    category: 'Makan & Bepergian',
    arabic: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ',
    latin: 'Bismillaahi tawakkaltu\'alallaah, laa haula wa laa quwwata illaa billaah.',
    translation: 'Dengan nama Allah, aku bertawakal kepada Allah, tiada daya dan kekuatan kecuali dengan pertolongan Allah.',
    source: 'HR. Abu Dawud & Tirmidzi',
  },
  {
    id: 'doa-17',
    number: 17,
    title: 'Doa Naik Kendaraan',
    category: 'Makan & Bepergian',
    arabic: 'بِسْمِ اللهِ مَجْرَهَا وَمُرْسَهَآ اِنَّ رَبِّىْ لَغَفُوْرٌ رَّحِيْمٌ',
    latin: 'Bismillaahi majrahaa wa mursaahaa inna robbii laghofuurur rohiim.',
    translation: 'Dengan nama Allah yang menjalankan kendaraan ini berlayar, berlabuh, sesungguhnya Tuhanku benar-benar Maha Pengampun lagi Maha Penyayang.',
    surahNumber: 11,
    surahName: 'Hud',
    verseNumber: 41,
    source: 'QS. Hud: 41',
  },
  {
    id: 'doa-18',
    number: 18,
    title: 'Doa Masuk Rumah',
    category: 'Makan & Bepergian',
    arabic: 'اللَّهُمَّ إِنِّى أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ بِاسْمِ اللَّهِ وَلَجْنا، وَبِاسْمِ اللَّهِ خَرَجْنا، وَعَلى اللَّهِ رَبِّنا تَوَكَّلْنا',
    latin: 'Allahumma inni as\'aluka khairal mauliji wa khairal makhraji bismillahi walajna wa bismillahi kharajna wa\'ala-llahi rabbina tawakkalna.',
    translation: 'Wahai Allah, aku memohon sebaik-baik tempat masuk dan sebaik-baik tempat keluar. Atas nama-Mu kami masuk dan atas nama-Mu kami keluar. Dan kepada Allah, kami bertawakal.',
    source: 'HR. Abu Dawud',
  },

  // 4. Doa Ibadah (19 - 24)
  {
    id: 'doa-19',
    number: 19,
    title: 'Doa Sebelum Wudhu',
    category: 'Ibadah',
    arabic: 'نَوَيْتُ الْوُضُوْءَ لِرَفْعِ الْحَدَثِ اْلاَصْغَرِ فَرْضًا لِلهِ تَعَالَى',
    latin: 'Nawaitul wudua lirof\'il hadatsii ashghori fardhon lillaahi ta\'alaa.',
    translation: 'Aku niat berwudu untuk menghilangkan hadas kecil, fardu karena Allah.',
    source: 'Niat Wudhu',
  },
  {
    id: 'doa-20',
    number: 20,
    title: 'Doa Setelah Wudhu',
    category: 'Ibadah',
    arabic: 'أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ. اللَّهُمَّ اجْعَلْنِى مِنَ التَّوَّابِينَ وَاجْعَلْنِى مِنَ الْمُتَطَهِّرِينَ',
    latin: 'Asyhadu allaa ilaaha illallah wahdahu laa syariikalahu. Wa asyhadu anna Muhammadan \'abduhu wa rasuuluhu. Allahumma-j\'alnii minattabinna waj\'alnii minal mutathohiirina waj\'alnii min \'ibadatishalihin.',
    translation: 'Aku bersaksi tiada Tuhan melainkan Allah dan tidak ada yang menyekutukan bagi-Nya. Dan aku bersaksi bahwa Nabi Muhammad adalah hamba-Nya dan utusan-Nya. Ya Allah jadikanlah aku orang yang ahli taubat dan jadikanlah aku orang yang suci dan jadikanlah aku dari golongan orang-orang yang saleh.',
    source: 'HR. Muslim & Tirmidzi',
  },
  {
    id: 'doa-21',
    number: 21,
    title: 'Doa Masuk Masjid',
    category: 'Ibadah',
    arabic: 'أَعُوْذُ بِاللهِ العَظِيْمِ وَبِوَجْهِهِ الْكَرِيْمِ وَسُلْطَانِهِ الْقَدِيْمِ مِنَ الشَّيْطَانِ الرَّجِيْمِ. بِسْمِ اللهِ وَالْحَمْدُ لِلهِ. أَللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ. اَللَّهُمَّ اغْفِرْ لِي ذُنُوْبِي وَافْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    latin: 'A\'udzu billahil\'azhim wa biwajhihil karim wa sulthanihil qadim minas syaithanir rajim. Bismillahi wal hamdulillah. Allahumma shalli wa salim\'ala sayyidina muhammadin wa\'ala ali sayyidina muhammadin. Allahummaghfirli dzunubi waftahli abwaba rahmatik.',
    translation: 'Aku berlindung kepada Allah Yang Maha Besar, kepada Dzat-Nya yang Maha Mulia, dan kepada kerajaan-Nya yang sedia dari setan yang terlontar. Dengan nama Allah dan segala puji bagi Allah. Wahai Tuhanku, berilah salawat dan sejahtera atas sayyidina Muhammad dan atas keluarga sayyidina Muhammad. Wahai Tuhanku, ampuni untukku segala dosaku. Buka lah bagiku segala pintu rahmat-Mu.',
    source: 'HR. Abu Dawud & Muslim',
  },
  {
    id: 'doa-22',
    number: 22,
    title: 'Doa Keluar Masjid',
    category: 'Ibadah',
    arabic: 'أَعُوْذُ بِاللهِ العَظِيْمِ وَبِوَجْهِهِ الْكَرِيْمِ وَسُلْطَانِهِ الْقَدِيْمِ مِنَ الشَّيْطَانِ الرَّجِيْمِ. بِسْمِ اللهِ وَالْحَمْدُ لِلهِ. أَللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ. اَللَّهُمَّ اغْفِرْ لِي ذُنُوْبِي وَافْتَحْ لِي أَبْوَابَ فَضْلِكَ',
    latin: 'A\'udzu billahil azhim wa biwajhihil karim wa sulthanihil qadim minas syaithanir rajim. Bismillahi walhamdulillah. Allahumma shalli wa sallim\'ala sayyidina muhammadin wa\'ala ali sayyidina Muhammadin. Allahummaghfirli dzunubi waftahli abwaba fadhlik.',
    translation: 'Aku berlindung kepada Allah Yang Maha Besar, kepada Dzat-Nya yang Maha Mulia, dan kepada kerajaan-Nya yang sedia dari setan yang terlontar. Dengan nama Allah dan segala puji bagi Allah. Wahai Tuhanku, berilah salawat dan sejahtera atas sayyidina Muhammad dan atas keluarga sayyidina Muhammad. Wahai Tuhanku, ampuni untukku segala dosaku. Buka lah bagiku segala pintu kemurahan-Mu.',
    source: 'HR. Abu Dawud & Ibnu Majah',
  },
  {
    id: 'doa-23',
    number: 23,
    title: 'Doa Setelah Adzan',
    category: 'Ibadah',
    arabic: 'اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيْلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُوْدًا الَّذِي وَعَدْتَهُ',
    latin: 'Allahumma rabba hadzihi ad-da\'wati at-taammati wash sholaatil qaa\'imati aati muhammadan al-wasiilata wal fadhiilata wab\'atshu maqaaman mahmuudan alladzi wa\'adtah.',
    translation: 'Ya Allah, pemilik seruan yang sempurna ini, dan shalat yang akan didirikan, berilah Muhammad wasilah dan keutamaan, dan bangkitkan untuknya kedudukan terpuji yang Engkau janjikan.',
    source: 'HR. Bukhari, dari Jabir bin Abdullah',
  },
  {
    id: 'doa-24',
    number: 24,
    title: 'Doa Setelah Sholat Fardhu',
    category: 'Ibadah',
    arabic: `بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم
اَلْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِيْنَ. حَمْدًا يُوَافِيْ نِعَمَهُ وَيُكَافِئُ مَزِيْدَهُ. يَا رَبَّنَا لَكَ الْحَمْدُ كَمَا يَنْبَغِيْ لِجَلاَلِ وَجْهِكَ الْكَرِيْمِ وَعَظِيْمِ سُلْطَانِكَ
اَللَّهُمَّ صَلِّ عَلىَ سَيِّدِنَا مُحَمَّدٍ وَعَلىَ آلِ سَيِّدِنَا مُحَمَّدٍ
اَللَّهُمَّ رَبَّنَا تَـقَـبَّلْ مِنَّا صَلاَتَنَا وَصِيَا مَنَا وَرُكُوْ عَنَا وَسُجُوْدَنَا وَقُعُوْدَنَا وَتَضَرُّ عَنَا وَتَخَشُّوْ عَنَا وَتَعَبُّدَنَا وَتَمِّمْ تَقْصِيْرَ نَا يَا اَلله يَا رَبَّ الْعَا لَمِيْنَ
رَبَّنَا ضَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْ حَمْنَا لَنَكُوْ نَنَّ مِنَ الْخَا سِرِ يْنَ
رَبَّنَا وَلاَ تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِ يْنَ مِنْ قَبْلِنَا
رَبَّنَا وَلاَ تُحَمِّلْنَا مَا لاَ طَا قَتَا لَنَا بِهِ, وَاعْفُ عَنَّا وَاغْفِرْلَنَا وَارْحَمْنَا أَنْتَ مَوْلاَ نَا فَا نْصُرْنَا عَلَى الْقَوْمِ الْكَا فِرِيْنَ
رَبَّنَا لاَ تُزِغْ قُلُوْ بَنَا بَعْدَ إِذْ هَدَ يْتَنَا وَهَبْ لَنَا مِنْ لَّدُ نْكَ رَحْمَةً إِنَّكَ أَنْتَ الْوَهَّابُ
رَبَّنَا اغْفِرْلَنَا وَلِوَالِدِيْنَ وَلِجَمِيْعِ الْمُسْلِمِيْنَ وَالْمُسْلِمَاتِ وَالْمُؤْمِنِيْنَ وَالْمُؤْمِنَاتِ أَلْأَ حْيَآءِ مِنْهُمْ وَاْلأَ مْوَاتِ, اِنَّكَ عَلَى كُلِّ شَيْءٍ قَدِيْرِ
رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي اْلآ خِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ
اللهم اغفر لنا ذنوبنا وكفرعنا سيئاتنا وتوفنا مَعَ الْأَ بْرَارِ
سُبْحَانَ رَبِّكِ رَبِّ الْعِزَّةِ عَمَّا يَصِفُوْنَ، وَسَلاَمٌ عَلَى الْمُرْ سَلِيْنَ، وَالْحَمْدُ لِلهِ رَبِّ الْعَالَمِيْنَ`,
    latin: `Bismillahirrahmaanirrahiim. Alhamdu lillaahi rabbil 'aalamiin, hamdan yuwaafii ni'amahu wayukaafii maziidahu. Ya rabbanaa lakal hamdu kamaa yan baghhi lijalaali wajhika wa'azhiimi sulthaanika. Allahumma shalli 'alaa sayyidinaa muhammadin wa'alaa aali sayyidinaa muhammad. Allahumma rabbanaa taqabbal minnaa shalaataana washiyaamanaa warukuu'anaa wasujuudanaa waqu'uudanaa watadlarru'anaa, watakhasysyu'anaa wata'abbudanaa, watammim taqshiiranaa yaa Allah yaa rabbal'aalamiin. Rabbana dzhalamnaa anfusanaa wa-inlamtaghfir lana watarhamnaa lanakuunanna minal khaasiriin. Rabbanaa walaa tahmil'alainaa ishran kama hamaltahul'alal ladziina min qablinaa. Rabbanaa walaa tuhammilnaa maalaa thaaqata lanaa bihii wa'fu'annaa waghfir lanaa warhamnaa anta maulaanaa fanshurnaa 'alal qaumil kaafiriin. Rabbanaa laa tuzigh quluubanaa ba'da idzhadaitanaa w'ahablanaa min ladunka rahmatan innaka antal wahhaab. Rabbanaghfir lanaa waliwaalidinaa walijami'il muslimiin walmuslimaati wal mu'miniina walmu'minati. Al ahyaa-i-minhum wal amwaati, innaka alaa kuli syai'n qadiir. Rabbanaa aatinaa fiddunyaa hasanatan wafil aakhirati hasanatan waqinaa adzaaban-naar. Allahummaghfirlanaa dzunuubanaa wakaffir annaa sayyiaatinaa watawaffanaa maalabraari. Subhaana rabbika rabbil i'zzati ammaa yashifuuna wasalaamun 'alal mursalhna wal-hamdu lillaahi rabbil'aalamiina.`,
    translation: `Dengan menyebut nama Allah Yang Maha Pengasih dan Maha Penyayang. Segala puji bagi Allah Tuhan seru sekalian alam. Dengan puji yang sebanding dengan nikmat-Nya dan menjamin tambahannya. Ya Allah Tuhan Kami, bagi-Mu segala puji dan segala apa yang patut atas keluhuran Dzat-Mu dan Keagungan kekuasaan-Mu. Ya Allah! Limpahkanlah rahmat dan salam atas junjungan kita Nabi Muhammad dan sanak keluarganya. Ya Allah terima sholat kami, puasa kami, ruku kami, sujud kami, duduk rebah kami, khusyu' kami, pengabdian kami, dan sempurnakanlah apa yang kami lakukan selama sholat ya Allah. Tuhan seru sekalian alam. Ya Allah, Kami telah aniaya terhadap diri kami sendiri, karena itu ya Allah jika tidak dengan limpahan ampunan-Mu dan rahmat-Mu niscaya kami akan jadi orang yang sesat. Ya Allah Tuhan kami, janganlah Engkau pikulkan atas diri kami beban yang berat sebagaimana yang pernah Engkau bebankan kepada orang yang terdahulu dari kami. Ya Allah Tuhan kami, janganlah Engkau bebankan atas diri kami apa yang di luar kesanggupan kami. Ampunilah dan limpahkanlah rahmat ampunan terhadap diri kami ya Allah. Ya Allah Tuhan kami, berilah kami pertolongan untuk melawan orang yang tidak suka kepada agama-Mu. Ya Allah Tuhan kami, janganlah Engkau sesatkan hati kami sesudah mendapat petunjuk, berilah kami karunia. Engkaulah yang maha Pemurah. Ya Allah Ya Tuhan kami, ampunilah dosa kami dan dosa-dosa orang tua kami, dan bagi semua orang Islam laki-laki dan perempuan, orang-orang mukmin laki-laki dan perempuan. Sesungguhnya Engkau dzat Yang Maha Kuasa atas segala-galanya. Maha suci Engkau, Tuhan segala kemuliaan. Suci dari segala apa yang dikatakan oleh orang-orang kafir. Semoga kesejahteraan atas para Rasul dan segala puji bagi Allah Tuhan seru sekalian alam.`,
    source: 'Doa Ba\'da Shalat Fardhu',
  },

  // 5. Doa Belajar dan Majelis (25 - 30)
  {
    id: 'doa-25',
    number: 25,
    title: 'Doa Kelancaran Berbicara',
    category: 'Belajar & Majelis',
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي',
    latin: 'Robbis rohlii shodrii, wa yassirlii amrii, wahlul \'uqdatam mil lisaani yafqohu qoulii.',
    translation: 'Ya Rabbku, lapangkanlah untukku dadaku, dan mudahkanlah untukku urusanku, dan lepaskanlah kekakuan dari lidahku, supaya mereka mengerti perkataanku.',
    surahNumber: 20,
    surahName: 'Taha',
    verseNumber: 25,
    source: 'QS. Thaha: 25-28',
  },
  {
    id: 'doa-26',
    number: 26,
    title: 'Doa Sebelum Belajar',
    category: 'Belajar & Majelis',
    arabic: 'يَارَبِّ زِدْنِىْ عِلْمًا وَارْزُقْنِىْ فَهْمًا',
    latin: 'Yaarobbi zidnii \'ilman warzuqnii fahmaa.',
    translation: 'Ya Allah, tambahkanlah aku ilmu dan berikanlah aku rizqi akan kepahaman.',
    source: 'Doa Penuntut Ilmu',
  },
  {
    id: 'doa-27',
    number: 27,
    title: 'Doa Selesai Belajar',
    category: 'Belajar & Majelis',
    arabic: 'اَللّٰهُمَّ اِنِّى اِسْتَوْدِعُكَ مَاعَلَّمْتَنِيْهِ فَارْدُدْهُ اِلَىَّ عِنْدَ حَاجَتِىْ وَلاَ تَنْسَنِيْهِ يَارَبَّ الْعَالَمِيْنَ',
    latin: 'Allaahumma innii astaudi\'uka maa \'allamtaniihi fardud-hu ilayya \'inda haajatii wa laa tansaniihi yaa robbal \'alamiin.',
    translation: 'Ya Allah, sesungguhnya aku menitipkan kepada Engkau ilmu-ilmu yang telah Engkau ajarkan kepadaku, dan kembalikanlah kepadaku sewaktu aku butuh kembali dan janganlah Engkau lupakan aku kepada ilmu itu wahai Tuhan seru sekalian alam.',
    source: 'Doa Pelajar Muslim',
  },
  {
    id: 'doa-28',
    number: 28,
    title: 'Doa Mohon Ilmu yang Bermanfaat',
    category: 'Belajar & Majelis',
    arabic: 'اَللّٰهُمَّ اِنِّى اَسْاَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا',
    latin: 'Allahumma innii as-aluka \'ilmaan naafi\'aan wa rizqoon thoyyibaan wa \'amalaan mutaqobbalaan.',
    translation: 'Ya Allah, sesungguhnya aku mohon kepada-Mu ilmu yang berguna, rezki yang baik dan amal yang baik diterima.',
    source: 'HR. Ibnu Majah',
  },
  {
    id: 'doa-29',
    number: 29,
    title: 'Doa Pembuka Majelis',
    category: 'Belajar & Majelis',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي هَدَانَا لِهَذَا وَمَا كُنَّا لِنَهْتَدِيَ لَوْلَا أَنْ هَدَانَا اللَّهُ',
    latin: 'Alḥamdu lillāhil-lażī hadānā lihāżā, wa mā kunnā linahtadiya lau lā an hadānallāh.',
    translation: 'Segala puji bagi Allah yang telah menunjuki kami kepada (surga) ini dan kami sekali-kali tidak akan mendapat petunjuk kalau Allah tidak memberi kami petunjuk.',
    surahNumber: 7,
    surahName: "Al-A'raf",
    verseNumber: 43,
    source: 'QS. Al-A\'raf: 43',
  },
  {
    id: 'doa-30',
    number: 30,
    title: 'Doa Penutup Majelis (Kafaratul Majelis)',
    category: 'Belajar & Majelis',
    arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ',
    latin: 'Subhanakallâhuma wa bihamdika, asyhadu an la ilaha illà anta, astaghfiruka wa atubu ilaik.',
    translation: 'Maha Suci Engkau, Ya Allah, aku memuji-Mu. Aku bersaksi bahwa tiada Tuhan kecuali Engkau, aku minta ampun dan bertobat kepada-Mu.',
    source: 'HR. Tirmidzi & Abu Dawud',
  },

  // 6. Doa Ketenangan Hati dan Rezeki (31 - 33)
  {
    id: 'doa-31',
    number: 31,
    title: 'Doa Penenang Hati dan Pikiran',
    category: 'Ketenangan & Rezeki',
    arabic: 'اللَّهُمَّ إِنِّى أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ وَالْجُبْنِ وَالْهَرَمِ وَالْبُخْلِ وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ',
    latin: 'Allahumma inni a\'udzu bika minal \'ajzi, wal kasali, wal jubni, wal haromi, wal bukhl. Wa a\'udzu bika min \'adzabil qobri wa min fitnatil mahyaa wal mamaat.',
    translation: 'Ya Allah, aku berlindung kepada-Mu dari kelemahan, rasa malas, rasa takut, kejelekan di waktu tua, dan sifat kikir. Dan aku juga berlindung kepada-Mu dari siksa kubur serta bencana kehidupan dan kematian.',
    source: 'HR. Bukhari & Muslim',
  },
  {
    id: 'doa-32',
    number: 32,
    title: 'Doa Pembuka Rezeki',
    category: 'Ketenangan & Rezeki',
    arabic: 'بِسْمِ اللهِ عَلَى نَفْسِي وَمَالِي وَدِيْنِيْ. اَللَّهُمَّ رَضِّنِيْ بِقَضَائِكَ، وَبَارِكْ لِيْ فِيْمَا قُدِّرَ لِيْ حَتَّى لَا أُحِبَّ تَعْجِيْلَ مَا أَخَّرْتَ وَلَا تَأْخِيْرَ مَا عَجَّلْتَ',
    latin: 'Bismillâhi \'ala nafsî wa mâlî wa dînî. Allâhumma radhdhinî bi qadhâ\'ika, wa bârik lî fîmâ quddira lî hattâ lâ uhibba ta\'jîla mâ akhkharta, wa lâ ta\'khîra mâ \'ajjalta.',
    translation: 'Dengan nama Allah yang menguasai diri, harta, dan agamaku. Tuhanku, kondisikan batinku agar rela menerima ketentuan-Mu. Berkatilah aku pada semua yang ditakdirkan untukku sehingga aku enggan menyegerakan apa yang Kautunda dan enggan menunda apa yang Kau segerakan.',
    source: 'HR. Ibnu Sunni',
  },
  {
    id: 'doa-33',
    number: 33,
    title: 'Doa Selamat Dunia Akhirat (Doa Sapu Jagat)',
    category: 'Ketenangan & Rezeki',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    latin: 'Rabbanā, ātinā fid dunyā hasanah, wa fil ākhirati hasanah, wa qinā \'adzāban nār.',
    translation: 'Tuhan kami, berikan kami kebaikan di dunia dan kebaikan di akhirat. Lindungilah kami dari siksa neraka.',
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    verseNumber: 201,
    source: 'QS. Al-Baqarah: 201',
  },

  // 7. Doa Keluarga dan Sesama (34 - 35)
  {
    id: 'doa-34',
    number: 34,
    title: 'Doa Kedua Orang Tua',
    category: 'Keluarga & Sesama',
    arabic: 'اَللّهُمَّ اغْفِرْلِيْ وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِيْ صَغِيْرَا',
    latin: 'Allohummaghfirlii waliwaalidayya war hamhumaa kamaa rabbayanii shaghiraa.',
    translation: 'Wahai Tuhanku, ampunilah aku dan kedua orang tuaku (Ibu dan Bapakku), sayangilah mereka seperti mereka menyayangiku di waktu kecil.',
    surahNumber: 17,
    surahName: "Al-Isra'",
    verseNumber: 24,
    source: 'QS. Al-Isra\': 24 & Doa Birrul Walidain',
  },
  {
    id: 'doa-35',
    number: 35,
    title: 'Doa Niat Puasa Ramadhan',
    category: 'Keluarga & Sesama',
    arabic: 'نَوَيْتُ صَوْمَ غَدٍ عَنْ أَدَاءِ فَرْضِ شَهْرِ رَمَضَانَ هَذِهِ السَّنَةِ لِلّٰهِ تَعَالَى',
    latin: 'Nawaitu shauma ghadin \'an ada\'i fardhi syahri Ramadhana hadzihis sanati lillahi ta\'ala.',
    translation: 'Aku niat berpuasa esok hari untuk menunaikan kewajiban puasa bulan Ramadhan tahun ini, karena Allah Ta\'ala.',
    source: 'Niat Puasa Ramadhan',
  },

  // 8. Doa Alam dan Musibah (36 - 37)
  {
    id: 'doa-36',
    number: 36,
    title: 'Doa Turun Hujan',
    category: 'Alam & Musibah',
    arabic: 'اَللَّهُمَّ صَيِّبًا هَنِيًّا وَسَيِّبًا نَافِعًا',
    latin: 'Allâhumma shayyiban haniyyâ wa sayyiban nâfi\'â.',
    translation: 'Wahai Tuhanku, jadikan ini hujan terpuji kesudahannya dan menjadi aliran air yang bermanfaat.',
    source: 'HR. Bukhari & Abu Dawud',
  },
  {
    id: 'doa-37',
    number: 37,
    title: 'Doa Mendengar Petir',
    category: 'Alam & Musibah',
    arabic: 'اَللَّهُمَّ لا تَقْتُلْنَا بِغَضَبِكَ وَلا تُهْلِكْنَا بِعَذَابِكَ وَعَافِنَا قَبْلَ ذَلِكَ',
    latin: 'Allahumma la taqtulna bighadhabika wala tuhlikna bi\'adzabika wa \'afina qabla dzalika.',
    translation: 'Ya Allah, janganlah Kau matikan kami dengan kemarahan-Mu, dan janganlah Kau rusak diriku dengan siksa-Mu, dan maafkanlah aku sebelum semua itu terjadi.',
    source: 'HR. Tirmidzi & Ahmad',
  },

  // 9. Doa Kesehatan dan Keselamatan (38 - 40)
  {
    id: 'doa-38',
    number: 38,
    title: 'Doa Minta Kesembuhan',
    category: 'Kesehatan & Keselamatan',
    arabic: 'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَاسِ اشْفِ أَنْتَ الشَّافِي لَا شَافِيَ إِلَّا أَنْتَ شِفَاءً لَا يُغَادِرُ سَقَمًا',
    latin: 'Allahumma rabban naasi adzhibil ba\'si isyfi antasy syaafi laa syaafiya illa anta syifaa\'an laa yughaadiru saqama.',
    translation: 'Ya Allah, Tuhan yang memelihara dan menguasai manusia, hapuskanlah penyakit dan penderitaan ini. Sembuhkanlah karena Engkaulah yang Maha Menyembuhkan. Tiada kesembuhan kecuali kesembuhan-Mu. Kesembuhan yang tidak menimbulkan efek samping.',
    source: 'HR. Bukhari, Muslim, Ahmad, & Abdurrazaq',
  },
  {
    id: 'doa-39',
    number: 39,
    title: 'Doa Untuk Orang Sakit',
    category: 'Kesehatan & Keselamatan',
    arabic: 'أَسْأَلُ اللهَ العَظِيْمَ رَبَّ العَرْشِ العَظِيْمِ أَنْ يَشْفِيَكَ',
    latin: 'As\'alullahal azhima rabbal \'arsyil \'azhimi an yassfiyaka.',
    translation: 'Aku memohon kepada Allah yang agung, Tuhan arasy yang megah agar menyembuhkanmu.',
    source: 'HR. Abu Dawud & Tirmidzi',
  },
  {
    id: 'doa-40',
    number: 40,
    title: 'Doa Untuk Orang Meninggal',
    category: 'Kesehatan & Keselamatan',
    arabic: 'السَّلَامُ عَلَيْكُمْ يَا أَهْلَ القُبُورِ يَغْفِرُ اللَّهُ لَنَا وَلَكُمْ، أَنْتُمْ سَلَفْنَا وَنَحْنُ بِالْأَثَرِ',
    latin: 'Assalaamu \'alaikum yaa ahlal qubuur yaghfirullaahu lanaa wa lakum antum salafnaa wa nahnu bil atsar.',
    translation: 'Semoga keselamatan terlimpah kepada kalian, wahai ahli kubur. Semoga Allah SWT mengampuni kami dan kalian, kalian adalah pendahulu kami dan kami akan menyusul kalian.',
    source: 'HR. Tirmidzi, dari Ibnu Abbas',
  },
];
