import { QariInfo, SurahListItem } from '@/types/quran';

export const QARI_LIST: QariInfo[] = [
  { id: '05', name: 'Misyari Rasyid Al-Afasi', country: 'Kuwait' },
  { id: '01', name: 'Abdullah Al-Juhany', country: 'Arab Saudi (Imam Masjidil Haram)' },
  { id: '03', name: 'Abdurrahman As-Sudais', country: 'Arab Saudi (Imam Masjidil Haram)' },
  { id: '02', name: 'Abdul Muhsin Al-Qasim', country: 'Arab Saudi (Imam Masjid Nabawi)' },
  { id: '04', name: 'Ibrahim Al-Dossari', country: 'Arab Saudi' },
];

export interface JuzInfo {
  juz: number;
  name: string;
  startSurah: number;
  startSurahName: string;
  startVerse: number;
  startArabic: string;
  endSurah: number;
  endSurahName: string;
  endVerse: number;
}

export const JUZ_METADATA: JuzInfo[] = [
  { juz: 1, name: "Al-Fatihah - Al-Baqarah", startSurah: 1, startSurahName: "Al-Fatihah", startVerse: 1, startArabic: "الفاتحة", endSurah: 2, endSurahName: "Al-Baqarah", endVerse: 141 },
  { juz: 2, name: "Al-Baqarah", startSurah: 2, startSurahName: "Al-Baqarah", startVerse: 142, startArabic: "سَيَقُولُ", endSurah: 2, endSurahName: "Al-Baqarah", endVerse: 252 },
  { juz: 3, name: "Al-Baqarah - Ali 'Imran", startSurah: 2, startSurahName: "Al-Baqarah", startVerse: 253, startArabic: "تِلْكَ الرُّسُلُ", endSurah: 3, endSurahName: "Ali 'Imran", endVerse: 92 },
  { juz: 4, name: "Ali 'Imran - An-Nisa'", startSurah: 3, startSurahName: "Ali 'Imran", startVerse: 93, startArabic: "لَنْ تَنَالُوا", endSurah: 4, endSurahName: "An-Nisa'", endVerse: 23 },
  { juz: 5, name: "An-Nisa'", startSurah: 4, startSurahName: "An-Nisa'", startVerse: 24, startArabic: "وَالْمُحْصَنَاتُ", endSurah: 4, endSurahName: "An-Nisa'", endVerse: 147 },
  { juz: 6, name: "An-Nisa' - Al-Ma'idah", startSurah: 4, startSurahName: "An-Nisa'", startVerse: 148, startArabic: "لَا يُحِبُّ اللَّهُ", endSurah: 5, endSurahName: "Al-Ma'idah", endVerse: 81 },
  { juz: 7, name: "Al-Ma'idah - Al-An'am", startSurah: 5, startSurahName: "Al-Ma'idah", startVerse: 82, startArabic: "لَتَجِدَنَّ", endSurah: 6, endSurahName: "Al-An'am", endVerse: 110 },
  { juz: 8, name: "Al-An'am - Al-A'raf", startSurah: 6, startSurahName: "Al-An'am", startVerse: 111, startArabic: "وَلَوْ أَنَّنَا", endSurah: 7, endSurahName: "Al-A'raf", endVerse: 87 },
  { juz: 9, name: "Al-A'raf - Al-Anfal", startSurah: 7, startSurahName: "Al-A'raf", startVerse: 88, startArabic: "قَالَ الْمَلَأُ", endSurah: 8, endSurahName: "Al-Anfal", endVerse: 40 },
  { juz: 10, name: "Al-Anfal - At-Taubah", startSurah: 8, startSurahName: "Al-Anfal", startVerse: 41, startArabic: "وَاعْلَمُوا", endSurah: 9, endSurahName: "At-Taubah", endVerse: 92 },
  { juz: 11, name: "At-Taubah - Hud", startSurah: 9, startSurahName: "At-Taubah", startVerse: 93, startArabic: "يَعْتَذِرُونَ", endSurah: 11, endSurahName: "Hud", endVerse: 5 },
  { juz: 12, name: "Hud - Yusuf", startSurah: 11, startSurahName: "Hud", startVerse: 6, startArabic: "وَمَا مِنْ دَابَّةٍ", endSurah: 12, endSurahName: "Yusuf", endVerse: 52 },
  { juz: 13, name: "Yusuf - Ibrahim", startSurah: 12, startSurahName: "Yusuf", startVerse: 53, startArabic: "وَمَا أُبَرِّئُ", endSurah: 14, endSurahName: "Ibrahim", endVerse: 52 },
  { juz: 14, name: "Al-Hijr - An-Nahl", startSurah: 15, startSurahName: "Al-Hijr", startVerse: 1, startArabic: "رُبَمَا", endSurah: 16, endSurahName: "An-Nahl", endVerse: 128 },
  { juz: 15, name: "Al-Isra' - Al-Kahf", startSurah: 17, startSurahName: "Al-Isra'", startVerse: 1, startArabic: "سُبْحَانَ الَّذِي", endSurah: 18, endSurahName: "Al-Kahf", endVerse: 74 },
  { juz: 16, name: "Al-Kahf - Taha", startSurah: 18, startSurahName: "Al-Kahf", startVerse: 75, startArabic: "قَالَ أَلَمْ أَقُلْ", endSurah: 20, endSurahName: "Taha", endVerse: 135 },
  { juz: 17, name: "Al-Anbiya' - Al-Hajj", startSurah: 21, startSurahName: "Al-Anbiya'", startVerse: 1, startArabic: "اقْتَرَبَ لِلنَّاسِ", endSurah: 22, endSurahName: "Al-Hajj", endVerse: 78 },
  { juz: 18, name: "Al-Mu'minun - Al-Furqan", startSurah: 23, startSurahName: "Al-Mu'minun", startVerse: 1, startArabic: "قَدْ أَفْلَحَ", endSurah: 25, endSurahName: "Al-Furqan", endVerse: 20 },
  { juz: 19, name: "Al-Furqan - An-Naml", startSurah: 25, startSurahName: "Al-Furqan", startVerse: 21, startArabic: "وَقَالَ الَّذِينَ", endSurah: 27, endSurahName: "An-Naml", endVerse: 55 },
  { juz: 20, name: "An-Naml - Al-'Ankabut", startSurah: 27, startSurahName: "An-Naml", startVerse: 56, startArabic: "فَمَا كَانَ", endSurah: 29, endSurahName: "Al-'Ankabut", endVerse: 45 },
  { juz: 21, name: "Al-'Ankabut - Al-Ahzab", startSurah: 29, startSurahName: "Al-'Ankabut", startVerse: 46, startArabic: "وَلَا تُجَادِلُوا", endSurah: 33, endSurahName: "Al-Ahzab", endVerse: 30 },
  { juz: 22, name: "Al-Ahzab - Yasin", startSurah: 33, startSurahName: "Al-Ahzab", startVerse: 31, startArabic: "وَمَنْ يَقْنُتْ", endSurah: 36, endSurahName: "Yasin", endVerse: 27 },
  { juz: 23, name: "Yasin - Az-Zumar", startSurah: 36, startSurahName: "Yasin", startVerse: 28, startArabic: "وَمَا أَنْزَلْنَا", endSurah: 39, endSurahName: "Az-Zumar", endVerse: 31 },
  { juz: 24, name: "Az-Zumar - Fussilat", startSurah: 39, startSurahName: "Az-Zumar", startVerse: 32, startArabic: "فَمَنْ أَظْلَمُ", endSurah: 41, endSurahName: "Fussilat", endVerse: 46 },
  { juz: 25, name: "Fussilat - Al-Jasiyah", startSurah: 41, startSurahName: "Fussilat", startVerse: 47, startArabic: "إِلَيْهِ يُرَدُّ", endSurah: 45, endSurahName: "Al-Jasiyah", endVerse: 37 },
  { juz: 26, name: "Al-Ahqaf - Az-Zariyat", startSurah: 46, startSurahName: "Al-Ahqaf", startVerse: 1, startArabic: "حم", endSurah: 51, endSurahName: "Az-Zariyat", endVerse: 30 },
  { juz: 27, name: "Az-Zariyat - Al-Hadid", startSurah: 51, startSurahName: "Az-Zariyat", startVerse: 31, startArabic: "قَالَ فَمَا خَطْبُكُمْ", endSurah: 57, endSurahName: "Al-Hadid", endVerse: 29 },
  { juz: 28, name: "Al-Mujadilah - At-Tahrim", startSurah: 58, startSurahName: "Al-Mujadilah", startVerse: 1, startArabic: "قَدْ سَمِعَ اللَّهُ", endSurah: 66, endSurahName: "At-Tahrim", endVerse: 12 },
  { juz: 29, name: "Al-Mulk - Al-Mursalat", startSurah: 67, startSurahName: "Al-Mulk", startVerse: 1, startArabic: "تَبَارَكَ الَّذِي", endSurah: 77, endSurahName: "Al-Mursalat", endVerse: 50 },
  { juz: 30, name: "An-Naba' - An-Nas (Juz 'Amma)", startSurah: 78, startSurahName: "An-Naba'", startVerse: 1, startArabic: "عَمَّ يَتَسَاءَلُونَ", endSurah: 114, endSurahName: "An-Nas", endVerse: 6 },
];

export const JUZ_LIST = JUZ_METADATA;

export { DAILY_DOA_LIST, DOA_CATEGORIES } from './doa-data';
export type { DailyDoaItem } from './doa-data';

export interface QuranDoa {
  id: string;
  title: string;
  arabic: string;
  translation: string;
  surahNumber: number;
  surahName: string;
  verseNumber: number;
  category: 'Keluarga' | 'Ampunan' | 'Keteguhan' | 'Kebaikan' | 'Kemudahan';
}

export const QURAN_DOA_LIST: QuranDoa[] = [
  {
    id: 'doa-1',
    title: 'Kebaikan Dunia & Akhirat (Doa Sapu Jagat)',
    arabic: 'رَبَّنَآ اٰتِنَا فِى الدُّنْيَا حَسَنَةً وَّفِى الْاٰخِرَةِ حَسَنَةً وَّقِنَا عَذَابَ النَّارِ',
    translation: 'Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka.',
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    verseNumber: 201,
    category: 'Kebaikan',
  },
  {
    id: 'doa-2',
    title: 'Keteguhan Iman & Memohon Rahmat',
    arabic: 'رَبَّنَا لَا تُزِغْ قُلُوْبَنَا بَعْدَ اِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَّدُنْكَ رَحْمَةً ۚ اِنَّكَ اَنْتَ الْوَهَّابُ',
    translation: 'Ya Tuhan kami, janganlah Engkau condongkan hati kami kepada kesesatan setelah Engkau berikan petunjuk kepada kami, dan karuniakanlah kepada kami rahmat dari sisi-Mu. Sesungguhnya Engkaulah Maha Pemberi.',
    surahNumber: 3,
    surahName: "Ali 'Imran",
    verseNumber: 8,
    category: 'Keteguhan',
  },
  {
    id: 'doa-3',
    title: 'Doa Pasangan & Keturunan Penyejuk Hati',
    arabic: 'رَبَّنَا هَبْ لَنَا مِنْ اَزْوَاجِنَا وَذُرِّيّٰتِنَا قُرَّةَ اَعْيُنٍ وَّاجْعَلْنَا لِلْمُتَّقِيْنَ اِمَامًا',
    translation: 'Ya Tuhan kami, anugerahkanlah kepada kami pasangan kami dan keturunan kami sebagai penyenang hati (kami), dan jadikanlah kami pemimpin bagi orang-orang yang bertakwa.',
    surahNumber: 25,
    surahName: 'Al-Furqan',
    verseNumber: 74,
    category: 'Keluarga',
  },
  {
    id: 'doa-4',
    title: 'Kelapangan Dada & Kemudahan Urusan (Nabi Musa AS)',
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي',
    translation: 'Ya Tuhanku, lapangkanlah dadaku, mudahkanlah untukku urusanku, dan lepaskanlah kekakuan dari lidahku, agar mereka mengerti perkataanku.',
    surahNumber: 20,
    surahName: 'Taha',
    verseNumber: 25,
    category: 'Kemudahan',
  },
  {
    id: 'doa-5',
    title: 'Ampunan Dosa & Pengakuan Kesalahan (Nabi Adam AS)',
    arabic: 'رَبَّنَا ظَلَمْنَآ اَنْفُسَنَا وَاِنْ لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُوْنَنَّ مِنَ الْخٰسِرِيْنَ',
    translation: 'Ya Tuhan kami, kami telah menzalimi diri kami sendiri. Jika Engkau tidak mengampuni kami dan memberi rahmat kepada kami, niscaya pastilah kami termasuk orang-orang yang rugi.',
    surahNumber: 7,
    surahName: "Al-A'raf",
    verseNumber: 23,
    category: 'Ampunan',
  },
  {
    id: 'doa-6',
    title: 'Keselamatan & Pertolongan Menghadapi Kesulitan (Nabi Yunus AS)',
    arabic: 'لَّآ اِلٰهَ اِلَّآ اَنْتَ سُبْحٰنَكَ اِنِّيْ كُنْتُ مِنَ الظّٰلِمِيْنَ',
    translation: 'Tidak ada tuhan selain Engkau, Mahasuci Engkau. Sungguh, aku termasuk orang-orang yang zalim.',
    surahNumber: 21,
    surahName: 'Al-Anbiya',
    verseNumber: 87,
    category: 'Ampunan',
  },
  {
    id: 'doa-7',
    title: 'Doa untuk Kedua Orang Tua',
    arabic: 'رَّبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    translation: 'Ya Tuhanku, ampunilah aku dan kedua orang tuaku, dan sayangilah keduanya sebagaimana mereka telah mendidikku pada waktu kecil.',
    surahNumber: 17,
    surahName: "Al-Isra'",
    verseNumber: 24,
    category: 'Keluarga',
  },
  {
    id: 'doa-8',
    title: 'Keturunan yang Saleh & Rajin Mendirikan Shalat',
    arabic: 'رَبِّ اجْعَلْنِيْ مُقِيْمَ الصَّلٰوةِ وَمِنْ ذُرِّيَّتِيْۖ رَبَّنَا وَتَقَبَّلْ دُعَاۤءِ',
    translation: 'Ya Tuhanku, jadikanlah aku dan anak cucuku orang-orang yang tetap mendirikan shalat, ya Tuhan kami, perkenankanlah doaku.',
    surahNumber: 14,
    surahName: 'Ibrahim',
    verseNumber: 40,
    category: 'Keluarga',
  },
];

export const SURAH_LIST_INITIAL: SurahListItem[] = [
  { nomor: 1, nama: "الفاتحة", namaLatin: "Al-Fatihah", jumlahAyat: 7, tempatTurun: "Mekah", arti: "Pembukaan" },
  { nomor: 2, nama: "البقرة", namaLatin: "Al-Baqarah", jumlahAyat: 286, tempatTurun: "Madinah", arti: "Sapi Betina" },
  { nomor: 3, nama: "آل عمران", namaLatin: "Ali 'Imran", jumlahAyat: 200, tempatTurun: "Madinah", arti: "Keluarga Imran" },
  { nomor: 4, nama: "النساء", namaLatin: "An-Nisa'", jumlahAyat: 176, tempatTurun: "Madinah", arti: "Wanita" },
  { nomor: 5, nama: "المائدة", namaLatin: "Al-Ma'idah", jumlahAyat: 120, tempatTurun: "Madinah", arti: "Hidangan" },
  { nomor: 6, nama: "الأنعام", namaLatin: "Al-An'am", jumlahAyat: 165, tempatTurun: "Mekah", arti: "Binatang Ternak" },
  { nomor: 7, nama: "الأعراف", namaLatin: "Al-A'raf", jumlahAyat: 206, tempatTurun: "Mekah", arti: "Tempat Tertinggi" },
  { nomor: 8, nama: "الأنفال", namaLatin: "Al-Anfal", jumlahAyat: 75, tempatTurun: "Madinah", arti: "Rampasan Perang" },
  { nomor: 9, nama: "التوبة", namaLatin: "At-Taubah", jumlahAyat: 129, tempatTurun: "Madinah", arti: "Pengampunan" },
  { nomor: 10, nama: "يونس", namaLatin: "Yunus", jumlahAyat: 109, tempatTurun: "Mekah", arti: "Yunus" },
  { nomor: 11, nama: "هود", namaLatin: "Hud", jumlahAyat: 123, tempatTurun: "Mekah", arti: "Hud" },
  { nomor: 12, nama: "يوسف", namaLatin: "Yusuf", jumlahAyat: 111, tempatTurun: "Mekah", arti: "Yusuf" },
  { nomor: 13, nama: "الرعد", namaLatin: "Ar-Ra'd", jumlahAyat: 43, tempatTurun: "Madinah", arti: "Guruh" },
  { nomor: 14, nama: "إبراهيم", namaLatin: "Ibrahim", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Ibrahim" },
  { nomor: 15, nama: "الحجر", namaLatin: "Al-Hijr", jumlahAyat: 99, tempatTurun: "Mekah", arti: "Bukit Bebatuan" },
  { nomor: 16, nama: "النحل", namaLatin: "An-Nahl", jumlahAyat: 128, tempatTurun: "Mekah", arti: "Lebah" },
  { nomor: 17, nama: "الإسراء", namaLatin: "Al-Isra'", jumlahAyat: 111, tempatTurun: "Mekah", arti: "Memperjalankan di Malam Hari" },
  { nomor: 18, nama: "الكهف", namaLatin: "Al-Kahf", jumlahAyat: 110, tempatTurun: "Mekah", arti: "Gua" },
  { nomor: 19, nama: "مريم", namaLatin: "Maryam", jumlahAyat: 98, tempatTurun: "Mekah", arti: "Maryam" },
  { nomor: 20, nama: "طه", namaLatin: "Taha", jumlahAyat: 135, tempatTurun: "Mekah", arti: "Taha" },
  { nomor: 21, nama: "الأنبياء", namaLatin: "Al-Anbiya'", jumlahAyat: 112, tempatTurun: "Mekah", arti: "Para Nabi" },
  { nomor: 22, nama: "الحج", namaLatin: "Al-Hajj", jumlahAyat: 78, tempatTurun: "Madinah", arti: "Haji" },
  { nomor: 23, nama: "المؤمنون", namaLatin: "Al-Mu'minun", jumlahAyat: 118, tempatTurun: "Mekah", arti: "Orang-Orang Mukmin" },
  { nomor: 24, nama: "النور", namaLatin: "An-Nur", jumlahAyat: 64, tempatTurun: "Madinah", arti: "Cahaya" },
  { nomor: 25, nama: "الفرقان", namaLatin: "Al-Furqan", jumlahAyat: 77, tempatTurun: "Mekah", arti: "Pembeda" },
  { nomor: 26, nama: "الشعراء", namaLatin: "Asy-Syu'ara'", jumlahAyat: 227, tempatTurun: "Mekah", arti: "Para Penyair" },
  { nomor: 27, nama: "النمل", namaLatin: "An-Naml", jumlahAyat: 93, tempatTurun: "Mekah", arti: "Semut" },
  { nomor: 28, nama: "القصص", namaLatin: "Al-Qasas", jumlahAyat: 88, tempatTurun: "Mekah", arti: "Cerita-Cerita" },
  { nomor: 29, nama: "العنكبوت", namaLatin: "Al-'Ankabut", jumlahAyat: 69, tempatTurun: "Mekah", arti: "Laba-Laba" },
  { nomor: 30, nama: "الروم", namaLatin: "Ar-Rum", jumlahAyat: 60, tempatTurun: "Mekah", arti: "Bangsa Romawi" },
  { nomor: 31, nama: "لقمان", namaLatin: "Luqman", jumlahAyat: 34, tempatTurun: "Mekah", arti: "Luqman" },
  { nomor: 32, nama: "السجدة", namaLatin: "As-Sajdah", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Sujud" },
  { nomor: 33, nama: "الأحزاب", namaLatin: "Al-Ahzab", jumlahAyat: 73, tempatTurun: "Madinah", arti: "Golongan yang Bersekutu" },
  { nomor: 34, nama: "سبإ", namaLatin: "Saba'", jumlahAyat: 54, tempatTurun: "Mekah", arti: "Kaum Saba'" },
  { nomor: 35, nama: "فاطر", namaLatin: "Fatir", jumlahAyat: 45, tempatTurun: "Mekah", arti: "Pencipta" },
  { nomor: 36, nama: "يس", namaLatin: "Yasin", jumlahAyat: 83, tempatTurun: "Mekah", arti: "Yasin" },
  { nomor: 37, nama: "الصافات", namaLatin: "As-Saffat", jumlahAyat: 182, tempatTurun: "Mekah", arti: "Barisan-Barisan" },
  { nomor: 38, nama: "ص", namaLatin: "Sad", jumlahAyat: 88, tempatTurun: "Mekah", arti: "Sad" },
  { nomor: 39, nama: "الزمر", namaLatin: "Az-Zumar", jumlahAyat: 75, tempatTurun: "Mekah", arti: "Rombongan" },
  { nomor: 40, nama: "غافر", namaLatin: "Gafir", jumlahAyat: 85, tempatTurun: "Mekah", arti: "Maha Pengampun" },
  { nomor: 41, nama: "فصلت", namaLatin: "Fussilat", jumlahAyat: 54, tempatTurun: "Mekah", arti: "Yang Dijelaskan" },
  { nomor: 42, nama: "الشورى", namaLatin: "Asy-Syura", jumlahAyat: 53, tempatTurun: "Mekah", arti: "Musyawarah" },
  { nomor: 43, nama: "الزخرف", namaLatin: "Az-Zukhruf", jumlahAyat: 89, tempatTurun: "Mekah", arti: "Perhiasan" },
  { nomor: 44, nama: "الدخان", namaLatin: "Ad-Dukhan", jumlahAyat: 59, tempatTurun: "Mekah", arti: "Kabut" },
  { nomor: 45, nama: "الجاثية", namaLatin: "Al-Jasiyah", jumlahAyat: 37, tempatTurun: "Mekah", arti: "Yang Berlutut" },
  { nomor: 46, nama: "الأحقاف", namaLatin: "Al-Ahqaf", jumlahAyat: 35, tempatTurun: "Mekah", arti: "Bukit-Bukit Pasir" },
  { nomor: 47, nama: "محمد", namaLatin: "Muhammad", jumlahAyat: 38, tempatTurun: "Madinah", arti: "Muhammad" },
  { nomor: 48, nama: "الفتح", namaLatin: "Al-Fath", jumlahAyat: 29, tempatTurun: "Madinah", arti: "Kemenangan" },
  { nomor: 49, nama: "الحجرات", namaLatin: "Al-Hujurat", jumlahAyat: 18, tempatTurun: "Madinah", arti: "Kamar-Kamar" },
  { nomor: 50, nama: "ق", namaLatin: "Qaf", jumlahAyat: 45, tempatTurun: "Mekah", arti: "Qaf" },
  { nomor: 51, nama: "الذاريات", namaLatin: "Az-Zariyat", jumlahAyat: 60, tempatTurun: "Mekah", arti: "Angin yang Menerbangkan" },
  { nomor: 52, nama: "الطور", namaLatin: "At-Tur", jumlahAyat: 49, tempatTurun: "Mekah", arti: "Bukit Tursina" },
  { nomor: 53, nama: "النجم", namaLatin: "An-Najm", jumlahAyat: 62, tempatTurun: "Mekah", arti: "Bintang" },
  { nomor: 54, nama: "القمر", namaLatin: "Al-Qamar", jumlahAyat: 55, tempatTurun: "Mekah", arti: "Bulan" },
  { nomor: 55, nama: "الرحمن", namaLatin: "Ar-Rahman", jumlahAyat: 78, tempatTurun: "Madinah", arti: "Maha Pengasih" },
  { nomor: 56, nama: "الواقعة", namaLatin: "Al-Waqi'ah", jumlahAyat: 96, tempatTurun: "Mekah", arti: "Hari Kiamat" },
  { nomor: 57, nama: "الحديد", namaLatin: "Al-Hadid", jumlahAyat: 29, tempatTurun: "Madinah", arti: "Besi" },
  { nomor: 58, nama: "المجادلة", namaLatin: "Al-Mujadilah", jumlahAyat: 22, tempatTurun: "Madinah", arti: "Gugatan" },
  { nomor: 59, nama: "الحشر", namaLatin: "Al-Hasyr", jumlahAyat: 24, tempatTurun: "Madinah", arti: "Pengusiran" },
  { nomor: 60, nama: "الممتحنة", namaLatin: "Al-Mumtahanah", jumlahAyat: 13, tempatTurun: "Madinah", arti: "Wanita yang Diuji" },
  { nomor: 61, nama: "الصف", namaLatin: "As-Saff", jumlahAyat: 14, tempatTurun: "Madinah", arti: "Barisan" },
  { nomor: 62, nama: "الجمعة", namaLatin: "Al-Jumu'ah", jumlahAyat: 11, tempatTurun: "Madinah", arti: "Jumat" },
  { nomor: 63, nama: "المنافقون", namaLatin: "Al-Munafiqun", jumlahAyat: 11, tempatTurun: "Madinah", arti: "Orang-Orang Munafik" },
  { nomor: 64, nama: "التغابن", namaLatin: "At-Tagabun", jumlahAyat: 18, tempatTurun: "Madinah", arti: "Pengungkapan Kesalahan" },
  { nomor: 65, nama: "الطلاق", namaLatin: "At-Talaq", jumlahAyat: 12, tempatTurun: "Madinah", arti: "Talak" },
  { nomor: 66, nama: "التحريم", namaLatin: "At-Tahrim", jumlahAyat: 12, tempatTurun: "Madinah", arti: "Pengharaman" },
  { nomor: 67, nama: "الملك", namaLatin: "Al-Mulk", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Kerajaan" },
  { nomor: 68, nama: "القلم", namaLatin: "Al-Qalam", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Pena" },
  { nomor: 69, nama: "الحاقة", namaLatin: "Al-Haqqah", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Hari Kiamat" },
  { nomor: 70, nama: "المعارج", namaLatin: "Al-Ma'arij", jumlahAyat: 44, tempatTurun: "Mekah", arti: "Tempat Naik" },
  { nomor: 71, nama: "نوح", namaLatin: "Nuh", jumlahAyat: 28, tempatTurun: "Mekah", arti: "Nuh" },
  { nomor: 72, nama: "الجن", namaLatin: "Al-Jinn", jumlahAyat: 28, tempatTurun: "Mekah", arti: "Jin" },
  { nomor: 73, nama: "المزمل", namaLatin: "Al-Muzzammil", jumlahAyat: 20, tempatTurun: "Mekah", arti: "Orang yang Berselimut" },
  { nomor: 74, nama: "المدثر", namaLatin: "Al-Muddassir", jumlahAyat: 56, tempatTurun: "Mekah", arti: "Orang yang Berkemul" },
  { nomor: 75, nama: "القيامة", namaLatin: "Al-Qiyamah", jumlahAyat: 40, tempatTurun: "Mekah", arti: "Hari Kiamat" },
  { nomor: 76, nama: "الإنسان", namaLatin: "Al-Insan", jumlahAyat: 31, tempatTurun: "Madinah", arti: "Manusia" },
  { nomor: 77, nama: "المرسلات", namaLatin: "Al-Mursalat", jumlahAyat: 50, tempatTurun: "Mekah", arti: "Malaikat-Malaikat yang Diutus" },
  { nomor: 78, nama: "النبإ", namaLatin: "An-Naba'", jumlahAyat: 40, tempatTurun: "Mekah", arti: "Berita Besar" },
  { nomor: 79, nama: "النازعات", namaLatin: "An-Nazi'at", jumlahAyat: 46, tempatTurun: "Mekah", arti: "Malaikat-Malaikat yang Mencabut" },
  { nomor: 80, nama: "عبس", namaLatin: "'Abasa", jumlahAyat: 42, tempatTurun: "Mekah", arti: "Ia Bermuka Masam" },
  { nomor: 81, nama: "التكوير", namaLatin: "At-Takwir", jumlahAyat: 29, tempatTurun: "Mekah", arti: "Penggulungan" },
  { nomor: 82, nama: "الانفطار", namaLatin: "Al-Infitar", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Terbelah" },
  { nomor: 83, nama: "المطففين", namaLatin: "Al-Mutaffifin", jumlahAyat: 36, tempatTurun: "Mekah", arti: "Orang-Orang Curang" },
  { nomor: 84, nama: "الانشقاق", namaLatin: "Al-Insyiqaq", jumlahAyat: 25, tempatTurun: "Mekah", arti: "Terbelah" },
  { nomor: 85, nama: "البروج", namaLatin: "Al-Buruj", jumlahAyat: 22, tempatTurun: "Mekah", arti: "Gugusan Bintang" },
  { nomor: 86, nama: "الطارق", namaLatin: "At-Tariq", jumlahAyat: 17, tempatTurun: "Mekah", arti: "Yang Datang di Malam Hari" },
  { nomor: 87, nama: "الأعلى", namaLatin: "Al-A'la", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Maha Tinggi" },
  { nomor: 88, nama: "الغاشية", namaLatin: "Al-Gasyiyah", jumlahAyat: 26, tempatTurun: "Mekah", arti: "Hari Pembalasan" },
  { nomor: 89, nama: "الفجر", namaLatin: "Al-Fajr", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Fajar" },
  { nomor: 90, nama: "البلد", namaLatin: "Al-Balad", jumlahAyat: 20, tempatTurun: "Mekah", arti: "Negeri" },
  { nomor: 91, nama: "الشمس", namaLatin: "Asy-Syams", jumlahAyat: 15, tempatTurun: "Mekah", arti: "Matahari" },
  { nomor: 92, nama: "الليل", namaLatin: "Al-Lail", jumlahAyat: 21, tempatTurun: "Mekah", arti: "Malam" },
  { nomor: 93, nama: "الضحى", namaLatin: "Ad-Duha", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Duha" },
  { nomor: 94, nama: "الشرح", namaLatin: "Asy-Syarh", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Kelapangan" },
  { nomor: 95, nama: "التين", namaLatin: "At-Tin", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Buah Tin" },
  { nomor: 96, nama: "العلق", namaLatin: "Al-'Alaq", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Segumpal Darah" },
  { nomor: 97, nama: "القدر", namaLatin: "Al-Qadr", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Kemuliaan" },
  { nomor: 98, nama: "البينة", namaLatin: "Al-Bayyinah", jumlahAyat: 8, tempatTurun: "Madinah", arti: "Bukti Nyata" },
  { nomor: 99, nama: "الزلزلة", namaLatin: "Az-Zalzalah", jumlahAyat: 8, tempatTurun: "Madinah", arti: "Guncangan" },
  { nomor: 100, nama: "العاديات", namaLatin: "Al-'Adiyat", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Kuda yang Berlari Kencang" },
  { nomor: 101, nama: "القارعة", namaLatin: "Al-Qari'ah", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Hari Kiamat yang Mengguncang" },
  { nomor: 102, nama: "التكاثر", namaLatin: "At-Takasur", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Bermegah-Megahan" },
  { nomor: 103, nama: "العصر", namaLatin: "Al-'Asr", jumlahAyat: 3, tempatTurun: "Mekah", arti: "Masa" },
  { nomor: 104, nama: "الهمزة", namaLatin: "Al-Humazah", jumlahAyat: 9, tempatTurun: "Mekah", arti: "Pengumpat" },
  { nomor: 105, nama: "الفيل", namaLatin: "Al-Fil", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Gajah" },
  { nomor: 106, nama: "قريش", namaLatin: "Quraisy", jumlahAyat: 4, tempatTurun: "Mekah", arti: "Suku Quraisy" },
  { nomor: 107, nama: "الماعون", namaLatin: "Al-Ma'un", jumlahAyat: 7, tempatTurun: "Mekah", arti: "Barang Berguna" },
  { nomor: 108, nama: "الكوثر", namaLatin: "Al-Kausar", jumlahAyat: 3, tempatTurun: "Mekah", arti: "Nikmat yang Banyak" },
  { nomor: 109, nama: "الكافرون", namaLatin: "Al-Kafirun", jumlahAyat: 6, tempatTurun: "Mekah", arti: "Orang-Orang Kafir" },
  { nomor: 110, nama: "النصر", namaLatin: "An-Nasr", jumlahAyat: 3, tempatTurun: "Madinah", arti: "Pertolongan" },
  { nomor: 111, nama: "اللهب", namaLatin: "Al-Lahab", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Gejolak Api" },
  { nomor: 112, nama: "الإخلاص", namaLatin: "Al-Ikhlas", jumlahAyat: 4, tempatTurun: "Mekah", arti: "Ikhlas" },
  { nomor: 113, nama: "الفلق", namaLatin: "Al-Falaq", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Waktu Subuh" },
  { nomor: 114, nama: "الناس", namaLatin: "An-Nas", jumlahAyat: 6, tempatTurun: "Mekah", arti: "Manusia" }
];
